version: '3'

services:
  controller:
    image: controller
    ports:
      - "9080:8080"
    environment:
      - GIN_MODE=release

  broker.aws.project:
    image: broker.aws.project
    ports:
      - "9081:8080"
    environment:
      - GIN_MODE=release

  broker.aws.environ:
    image: broker.aws.environ
    ports:
      - "9082:8080"
    environment:
      - GIN_MODE=release

  broker.aws.database:
    image: broker.aws.database
    ports:
      - "9083:8080"
    environment:
      - GIN_MODE=release

  broker.aws.cache:
    image: broker.aws.cache
    ports:
      - "9084:8080"
    environment:
      - GIN_MODE=release

  broker.aws.compute:
    image: broker.aws.compute
    ports:
      - "9085:8080"
    environment:
      - GIN_MODE=release
