AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Environment

Parameters:
  ProjectName:
    Description: ""
    Type: String
  EnvironName:
    Description: ""
    Type: String

Outputs:
  ProjectName:
    Value: !Ref ProjectName
  EnvironName:
    Value: !Ref EnvironName
  InternetFacingSecurityGroup:
    Value: !Ref InternetFacingSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-InternetFacingSecurityGroup
  ApplicationSecurityGroup:
    Value: !Ref ApplicationSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-ApplicationSecurityGroup
  BackendSecurityGroup:
    Value: !Ref BackendSecurityGroup
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-BackendSecurityGroup
  EC2InstanceProfile:
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-EC2InstanceProfile

Resources:
  InternetFacingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PublicSecurityGroup
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VPC" }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}.${EnvironName}.internet-facing
        - Key: ProjectName
          Value: !Ref ProjectName

  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ApplicationSecurityGroup
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VPC" }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}.${EnvironName}.application
        - Key: ProjectName
          Value: !Ref ProjectName

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PrivateSecurityGroup
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-VPC" }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}.${EnvironName}.backend
        - Key: ProjectName
          Value: !Ref ProjectName

  S3BucketLog:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub
        - ${EnvironName}-log.${ProjectName}.${DomainName}
        - { "DomainName": { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-DomainName" } }}
      Tags:
        - Key: Name
          Value: !Sub ${EnvironName}-log.${ProjectName}.${DomainName}
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironName
          Value: !Ref EnvironName

  S3BucketLogPolicy:
    DependsOn: S3BucketLog
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketLog
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ALBLogBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                - 582318560864 # ap-northeast-1
                - 127311923021 # us-east-1
                - 033677994240 # us-east-2
                - 027434742980 # us-west-1
                - 797873946194 # us-west-2
            Action: s3:PutObject
            Resource: !Sub
              - arn:aws:s3:::${S3BucketLog}/AWSLogs/${AccountId}/*
              - { "AccountId": { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-AccountId" } }}
