AWSTemplateFormatVersion: '2010-09-09'

Description:
  AWS Relational Database Service

Parameters:
  ProjectName:
    Description: ""
    Type: String
  EnvironName:
    Description: ""
    Type: String
  InstanceName:
    Description: ""
    Type: String
  MasterUsername:
    Description: ""
    Type: String
  MasterPassword:
    Description: ""
    Type: String

Outputs:
  ProjectName:
    Value: !Ref ProjectName
  EnvironName:
    Value: !Ref EnvironName
  InstanceName:
    Value: !Ref InstanceName
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-Database-InstanceName
  ReadEndpoint:
    Value: !Sub
      - ${EnvironName}-${InstanceName}.read.${ProjectName}.${DomainName}
      - { "DomainName": { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-DomainName" } }}
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-Database-${InstanceName}-ReadEndpoint
  WriteEndpoint:
    Value: !Sub
      - ${EnvironName}-${InstanceName}.write.${ProjectName}.${DomainName}
      - { "DomainName": { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-DomainName" } }}
    Export:
      Name: !Sub ${ProjectName}-${EnvironName}-Database-${InstanceName}-WriteEndpoint

Resources:
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-${EnvironName}-BackendSecurityGroup" } }
      SourceSecurityGroupId: { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-${EnvironName}-ApplicationSecurityGroup" } }
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306

  ParameterStoreEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Description: InternalEndpoint
      Type: String
      Name: !Sub ${ProjectName}_${EnvironName}_${InstanceName}_endpoint_read
      Value: !Sub
        - ${EnvironName}-${InstanceName}.read.${ProjectName}.${DomainName}
        - { "DomainName": { "Fn::ImportValue" : {"Fn::Sub": "${ProjectName}-DomainName" } }}
